# title: (☝︎ ՞ਊ ՞)☝︎
title: " "
# description: I see you, baby, shaking that apsis
# logo: http://i.imgur.com/ImZLPFn.jpg
# logo: https://i.imgur.com/YYefakX.gif
logo: /assets/images/hiclipart1.png
remote_theme: pmarsceill/just-the-docs
color_scheme: "dark"
